import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./Provider";
import { Outfit as OutfitFont } from 'next/font/google'; // Renamed the import

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfitFont = OutfitFont({ subsets: ['latin'] }); // Renamed the constant
export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={outfitFont.className}>
          <Provider>
            {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
